In [102]:
import cv2
import os
os.chdir('C:\\Users\\agadiya\\Desktop\\Deloitte Others\\PythonLearn\\opencv')

In [103]:
img= cv2.imread("galaxy.jpg",1)

In [104]:
type(img)

numpy.ndarray

In [105]:
print(img)

[[[19 15 10]
  [23 19 14]
  [21 15  8]
  ...
  [27 22 13]
  [22 17  8]
  [23 18  9]]

 [[17 13  8]
  [21 17 12]
  [19 13  6]
  ...
  [27 22 13]
  [22 17  8]
  [24 19 10]]

 [[17 14  6]
  [18 15  7]
  [21 18 10]
  ...
  [23 16  7]
  [33 26 17]
  [30 23 14]]

 ...

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 5  5  5]
  [ 8  8  8]
  [14 14 14]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 2  2  2]
  [ 3  3  3]
  [ 9  9  9]]

 [[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [ 1  1  1]
  [ 1  1  1]
  [ 3  3  3]]]


In [106]:
img.shape

(1485, 990, 3)

In [107]:
resized_img= cv2.resize(img,(1000,500))

In [108]:
cv2.imshow("galaxy.jpg",resized_img)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [109]:
# Face detection begins here

In [110]:
import cv2
os.chdir('C:\\Users\\agadiya\\Desktop\\Deloitte Others\\PythonLearn\\opencv\\Files')
face_cascade = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")
face_cascade

<CascadeClassifier 00000233B8D39270>

In [111]:
img=cv2.imread("IMG_A.jpg")

In [112]:
cv2.imshow("IMG_A.jpg",img)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [113]:
gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces_gray=face_cascade.detectMultiScale(gray_img,scaleFactor=1.07,minNeighbors=2)

In [114]:
print(faces_gray)

[[470 275  30  30]
 [382  23 208 208]]


In [115]:
faces_original=face_cascade.detectMultiScale(img,scaleFactor=1.03,minNeighbors=3)

In [116]:
print(faces_original)

[[469 275  32  32]
 [145 298  34  34]
 [385  29 201 201]
 [531 316  64  64]]


In [117]:
#Adding the rectangle in the image

for x,y,w,h in faces_original:
    img=cv2.rectangle(img, (x,y), (x+w,y+h),(0,255,0),2)

cv2.imshow("Akash.jpg",img)
cv2.waitKey(0)
cv2.destroyAllWindows()


# Capturing a video

In [66]:
import time, cv2
video=cv2.VideoCapture(0)

while True:
    check, frame = video.read()
    print(check)

    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)

    #time.sleep(3)
    cv2.imshow("Capturing", gray)
    key= cv2.waitKey(2000)
    
    if key==ord('q'):
        break

video.release()
cv2.destroyAllWindows()

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
